DROP TABLE USER_ID;
CREATE TABLE USER_ID (
	USER_KEY INT(1) NOT NULL AUTO_INCREMENT,
	EMAIL_ID VARCHAR(255) NOT NULL,
	PASSWD VARCHAR(255)  NOT NULL,
	REGIST_DATE TIMESTAMP,
	PRIMARY KEY(USER_KEY,EMAIL_ID,PASSWD)
);
CREATE TABLE USER_INFM (
	USER_KEY INT(1),
	NAME VARCHAR(255),
	PHONE VARCHAR(255),
	ADDRESS VARCHAR(255),
	ADDRESS_NUM VARCHAR(255),
	FOREIGN KEY(USER_KEY)
	REFERENCES USER_ID(USER_KEY) ON UPDATE CASCADE
);

